"""
Alembic Migration: Add refresh_tokens table

This migration adds the refresh_tokens table to support the refresh token pattern.

To use this:
  1. Install alembic: pip install alembic
  2. Initialize alembic: alembic init migrations
  3. Create migration: alembic revision --autogenerate -m "Add refresh tokens"
  4. Apply migration: alembic upgrade head

This file is a manually-created migration (not autogenerated).
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002_add_refresh_tokens'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    """Create refresh_tokens table"""
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token_id', sa.String(), nullable=False),  # JWT ID (jti)
        sa.Column('token_hash', sa.String(), nullable=False),  # Hashed token
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('is_rotated', sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token_id', name='uq_refresh_tokens_token_id'),
    )
    
    # Add indexes for performance
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'])
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'])
    op.create_index('ix_refresh_tokens_token_id', 'refresh_tokens', ['token_id'])

def downgrade():
    """Drop refresh_tokens table"""
    op.drop_index('ix_refresh_tokens_token_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
